version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/laravel-pilot-app
    environment:
        - CIRCLE_PROJECT_REPONAME: laravel-pilot-app

    steps:
        - checkout
        - run: docker-compose up -d
        - run: docker-compose exec php composer install -n --prefer-dist
        - run: newman run https://api.getpostman.com/collections/${POSTMAN_COLLECTION_ID}?apikey=${POSTMAN_API_KEY} -e https://api.getpostman.com/environments/${POSTMAN_ENV_ID}?apikey=${POSTMAN_API_KEY}